DRDetection/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from DRDetection import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('DiabeticRetinopathy.urls')),
]

if settings.DEBUG:
    #urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DiabeticRetinopathy/urls.py
from django.contrib import admin
from django.urls import path, include

from DiabeticRetinopathy import views
app_name = 'DR'
urlpatterns = [
    path('',views.homeview,name='homeview'),
    path('user_logout/',views.user_logout, name = 'user_logout'),
    path('team',views.teamview, name = 'teamview')

]

DiabeticRetinopathy/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
import uuid
from datetime import datetime

from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.db import models


GENDER_OPTIONS = (
                ('Male','Male'),
                ('Female','Female'),
                )


class UserManager(BaseUserManager):

    def create_user(self,email,password=None):
        if not email:
            raise ValueError("Please enter an email")

        user = self.model(
            email = self.normalize_email(email),
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,email,password):
        user = self.create_user(email, password=password)
        user.admin = True
        user.staff = True
        user.host = True
        user.save(using=self._db)
        return user

    def create_staff(self,email,password):
        user = self.create_user(email,password=password)
        user.staff = True
        user.save(using=self._db)
        return user

class User(AbstractBaseUser):
    first_name = models.CharField(max_length=255, blank=False)
    last_name = models.CharField(max_length=255, blank=False,null=True)
    oname = models.CharField(max_length=255, blank=False, null=True)
    bdate = models.DateField(null=True)
    user_id = models.UUIDField(unique=True, default=uuid.uuid4)
    email = models.EmailField(max_length=255, unique=True)
    staff = models.BooleanField(default=False)
    admin = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()


    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_admin(self):
        return self.admin

    @property
    def is_staff(self):
        return self.staff

class Report(models.Model):
    uuid = models.UUIDField(unique=True, default=uuid.uuid4)
    first_name = models.CharField(max_length=255, blank=False, null=False)
    last_name = models.CharField(max_length=255, blank=False, null=False)
    age = models.PositiveIntegerField(blank=False, null=False)
    gender = models.CharField(max_length=10,null = True, choices=GENDER_OPTIONS)
    date = models.DateTimeField(default=datetime.now())
    photo = models.ImageField(upload_to='fundus_images',null=True)

DiabeticRetinopathy/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from DiabeticRetinopathy.models import User
from django.db.models import Q
from django.forms import TextInput, ModelForm
from django import forms
from DiabeticRetinopathy.models import Report

GENDER_OPTIONS = (
                ('Male','Male'),
                ('Female','Female'),
                )


class RegisterForm(UserCreationForm):
    password1 = forms.CharField(label="Password",widget=forms.PasswordInput)
    password2 = forms.CharField(label="Confirm Password",widget=forms.PasswordInput)

    first_name = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))

    last_name = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))

    oname = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))

    email = forms.EmailField(label="Email", widget=forms.EmailInput(
        attrs={
            'class': 'form-control'
        }
    ))

    bdate = forms.DateField(label='bdate', widget=forms.DateInput(
        attrs={
            'class': 'form-control',
            'type': 'date'
        }
    ))


    class Meta:
        model = get_user_model()
        fields = ('first_name','last_name','oname','email','bdate')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email is already taken")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")
        return password2

    def save(self, commit=True):
        if self.clean_email() and self.clean_password2():
            user = super(RegisterForm, self).save(commit=False)
            user.set_password(self.cleaned_data.get('password1'))
            if commit:
                user.save()
            return user
        else:
            raise ValueError("Error in form")


class LoginForm(forms.Form):
    email = forms.EmailField(label="Email",widget=forms.EmailInput(
        attrs={
            'class':'form-control'
        }
    ))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class':'form-control'
        }
    ),label="Password")

    def clean(self, *args, **kwargs):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')

        user_final = User.objects.filter(
            Q(email__iexact = email)
        ).distinct()

        if not user_final.exists() and user_final.count() != 1:
            raise forms.ValidationError("Invalid credentials. User does not exist")

        user_obj = user_final.first()
        if not user_obj.check_password(password):
            raise forms.ValidationError("Password incorrect")

        self.cleaned_data['user_obj'] = user_obj
        return super(LoginForm, self).clean()

class ReportForm(forms.ModelForm):
    first_name = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))

    last_name = forms.CharField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))

    age = forms.IntegerField(widget=TextInput(
        attrs={
            'class': 'form-control'
        }
    ))

    gender = forms.ChoiceField(choices=GENDER_OPTIONS,required=True)


    class Meta:
        model = Report
        fields = ('first_name','last_name','age','gender','photo')

DiabeticRetinopathy/views.py
import base64
from fastai.vision import *


from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse
from django.shortcuts import render, redirect



# Create your views here.
from DiabeticRetinopathy.forms import RegisterForm, LoginForm, ReportForm
from DiabeticRetinopathy.models import Report
from .render import Render




def homeview(request):
    global load_learner
    if not request.user.is_authenticated:
        if request.method == 'POST' and 'register' in request.POST:
            registerform = RegisterForm(request.POST)
            if registerform.is_valid():
                user = registerform.save()
                new_user = authenticate(email=registerform.cleaned_data['email'],
                                        password=registerform.cleaned_data['password1'],
                                        )
                login(request, new_user)
                return redirect('DR:homeview')
            else:
                return HttpResponse('{}'.format(registerform.errors))
        elif request.method == 'POST' and 'login' in request.POST:
            loginform = LoginForm(request.POST)
            if loginform.is_valid():
                user_obj = loginform.cleaned_data.get('user_obj')
                login(request, user_obj)
                return redirect('DR:homeview')
            else:
                return HttpResponse('{}'.format(loginform.errors))
        else:
            loginform = LoginForm()
            registerform = RegisterForm()
            return render(request,'DiabeticRetinopathy/login.html',{'loginform': loginform, 'registerform':registerform})
    else:
        if request.method == 'POST':
            if 'upload' in request.POST:
                reportform = ReportForm(request.POST, request.FILES)
                if reportform.is_valid():
                    report = reportform.save()
                    report = Report.objects.get(uuid__exact=report.uuid)
                    learn = load_learner('')
                    category = learn.predict(open_image(report.photo.path))[0]
                    request.session['category'] = category.__int__()
                    params = {
                        'first_name': report.first_name,
                        'last_name': report.last_name,
                        'age': report.age,
                        'gender': report.gender,
                        'photo': report.photo,
                        'date1': report.date,
                        'category': request.session.get('category'),
                        'pid': report.uuid
                    }
                    return render(request,'DiabeticRetinopathy/report.html',params)
            if 'Download' in request.POST:
                report = Report.objects.latest('date')
                params = {
                'first_name'    : report.first_name,
                'last_name'     : report.last_name,
                'age'           : report.age,
                'gender'        : report.gender,
                'photo'         : report.photo,
                'date1'         : report.date,
                'category'      : request.session.get('category')
                }
                return Render.render('DiabeticRetinopathy/pdf.html', params)
        reportform = ReportForm()
        return render(request,'DiabeticRetinopathy/upload.html',{'reportform':reportform})

def user_logout(request):
    logout(request)
    return redirect('DR:homeview')

def teamview(request):
    return render(request,'DiabeticRetinopathy/team.html')

DiabeticRetinopathy/templates/DiabeticRetinopathy/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>dr-detection</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'DiabeticRetinopathy/style.css' %}">

<style>
    legend {
  display: block;
  padding-left: 2px;
  padding-right: 2px;
  border: none;
}
</style>

</head>

<body>

    <nav class="navbar bg-dark navbar-expand-sm">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="upload.html"><i class="fa fa-eye" style="font-size: 35px; "></i></a>
          </div>
          
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item"><a href = "{% url 'DR:homeview' %}"><be>Login</b></a></li>
            <li class="nav-item"><a href="#"><be>About</b></a></li>
            <li class="nav-item"><a href="{% url 'DR:teamview' %}"><be>Team</b></a></li>
          </ul>
        </div>
    </nav>

    <br><br>

    <div class="header">
        <div class="jumbotron">
            <i class="fa fa-eye icon" style="display: inline-block; color: rgb(166, 183, 39);"><br>Diabetic Retinopathy Detection  </i>
        </div>
    </div>

    <br>
    <div class="login-module">

        <div class="row">

            <div class="col-lg-6">
                <div class="jumbotron">
                    <form action="" method="post">
                        {% csrf_token %}
                    <fieldset style="color: seashell;">
                        <legend style="color: rgb(166, 183, 39);"> <center><b>Login</b></center>    </legend> <br>
                        <label for="email">Email:</label>
                        {{ loginform.email }}<br><br>

                        <label for="passwd">Password:</label>                        
                        {{ loginform.password }}<br><br>
                        
                        <center>
                        <input type="submit" class="btn btn-outline-light" style="width: 150px;" value="Login" name="login">
                        </center>
                    </fieldset>
                    
                    </form>

                </div>
            </div>

            <div class="col-lg-6">
                <div class="jumbotron">
                    <form action="" method="post">
                        {% csrf_token %}
                    <fieldset style="color: seashell;">
                        <legend style="color: rgb(166, 183, 39);"> <center><b>Registration</b></center>    </legend> <br>
                        <label for="fname">First name:</label>
                        {{ registerform.first_name }}<br><br>
                        <label for="lname">Last name:</label>
                        {{ registerform.last_name }}<br><br>
                        <label for="oname">Organization:</label>
                        {{ registerform.oname }}<br><br>
                        <label for="email">Email:</label>
                        {{ registerform.email }}<br><br>
                        <label for="birthday">Birthday:</label>                        
                        {{ registerform.bdate }}<br><br>
                        <label for="passwd">Password:</label>                        
                        {{ registerform.password1 }}<br><br>
                        <label for="passwd2">Password:</label>                        
                        {{ registerform.password2 }}<br><br>
                        <center>
                        <input type="submit" class="btn btn-outline-light" style="width: 150px;" value="Register" name="register">
                        </center>
                    </fieldset>
                    </form>

                </div>
            </div>
        </div>


    </div>



    <br><br>
    <footer><hr>BE Project<br>Diabetic Retinopathy Detection <br>Group 23 <br> <br></footer>
    
</body>

</html>

DiabeticRetinopathy/templates/DiabeticRetinopathy/pdf.html
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Diabetic Retinopathy Report</title>
    <style type="text/css">
        @page {
            size: A4;
            margin: 1cm;
        }

        .table {
            width: 100%;
            max-width: 100%;
            margin-bottom: 5px;
            background-color: #fff;
        }

        .table th,
        .table td {
            padding: 5px;
            vertical-align: top;
            border-top: 1px solid #000;
            text-align: center;
        }

        .table thead th {
            vertical-align: bottom;
            border-bottom: 2px solid #000;
        }

        .table tbody + tbody {
            border-top: 2px solid #000;
        }

        .table .table {
            background-color: #fff;
        }

        .list-group {
            display: block;
            width: 100%;
            list-style: none;
            margin-top: 15px;
            margin-bottom: 15px;
        }

        .list-group p {
            width: 100%;
            height: 20px;
            line-height: 20px;
            list-style: none;
            font-size: 1.1em;
        }

    </style>
</head>
<body>

<div class="container">
    <div class="card">
        <div class="card-header">
            <h3>Diabetic Retinopathy Report - {{ date1 | date:"d/m/Y" }}</h3>
        </div>

        <div class="list-group">
            <p>Name : {{ first_name }} {{ last_name }}</p>
            <p>Age : {{ age }}</p>
            <p>Gender : {{ gender }}</p>
        </div>

        <table class="table">
            <thead>
            <tr>
                <th>Photo</th>
                <th>Diagnosis</th>
            </tr>
            </thead>
            <tbody>
                <tr>
                    <td><img src="{{ photo.path }}" width="200px" height="200px" alt="haha"></td>
                    <td>Stage {{ category }}</td>
                </tr>
            </tbody>
        </table>

    </div>
</div>

</body>
</html>

DiabeticRetinopathy/templates/DiabeticRetinopathy/report.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'DiabeticRetinopathy/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>


<body>

    <nav class="navbar bg-dark navbar-expand-sm">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="upload.html"><i class="fa fa-eye" style="font-size: 35px; "></i></a>
          </div>
          
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item"><a href="login.html"><be>Login</b></a></li>
            <li class="nav-item"><a href="#"><be>About</b></a></li>
            <li class="nav-item"><a href="team.html"><be>Team</b></a></li>
          </ul>
        </div>
    </nav>
    <br>

    <div class="jumbotron">
        <h1 style="margin-left: 550px; color: rgb(166, 183, 39);">RESULT</h1><br>
        <div class="upload-body">

            
            <br>
            <div id="info-table" class="info-table">
                <table>

                    <tr>
                        <td><b>Patient ID</b></td>
                        <td>:</td>
                        <td>{{ pid }}</td>
                    </tr>
                    
                    <tr>
                        <td><b>NAME</b></td>
                        <td>:</td>
                        <td>{{ first_name }} {{ last_name }}</td>
                    </tr>

                    <tr>
                        <td><b>AGE</b></td>
                        <td>:</td>
                        <td>{{ age }}</td>
                    </tr>

                    <tr>
                        <td><b>GENDER</b></td>
                        <td>:</td>
                        <td>{{ gender }}</td>
                    </tr>

                    <tr>
                        <td colspan="3">
                            <img src="{{ photo.url }}" alt="uploaded_fundus" width="512px" height="512px">
                        </td>
                        
                    </tr>
                    <!-- If you want to display name age and gender here too, just add nore trs-->
                    <tr>
                        <td><b>CATEGORY</b></td>
                        <td>:</td>
                        <td>{{ category }}</td>
                    </tr>
                    <tr>
                        <td colspan="3">
                            <form method="post" action="" enctype="multipart/form-data">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-outline-light btn-add" name="Download">Download Report</button>
                            </form>
                        </td>
                    </tr>
                </table>

            </div>

        </div>
    </div>

    <br><br>
    <footer><hr>BE Project<br>Diabetic Retinopathy Detection <br>Group 23 <br> <br></footer>
    



</body>
</html>



<!--
<body>
    <div class="container" align="center">
    <h3>Report</h3>
        <img src="{{ photo.url }}" alt="haha" width="512px" height="512px">
        <h1>CATEGORY : {{ category }}</h1>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" class="btn btn-default" name="Download">Download Report</button>
        </form>
    </div>
</body>
</html>
-->

DiabeticRetinopathy/templates/DiabeticRetinopathy/report_org.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Report</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container" align="center">
    <h3>Report</h3>
        <img src="{{ photo.url }}" alt="haha" width="512px" height="512px">
        <h1>CATEGORY : {{ category }}</h1>
        <form method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" class="btn btn-default" name="Download">Download Report</button>
        </form>
    </div>
</body>
</html>

DiabeticRetinopathy/templates/DiabeticRetinopathy/template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>dr-detection</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="style.css">
</head>

<body>

    <nav class="navbar bg-dark navbar-expand-sm">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="upload.html"><i class="fa fa-eye" style="font-size: 35px; "></i></a>
          </div>
          
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item"><a href="login.html"><be>Login</b></a></li>
            <li class="nav-item"><a href="#"><be>About</b></a></li>
            <li class="nav-item"><a href="team.html"><be>Team</b></a></li>
          </ul>
        </div>
    </nav>

    <br><br>

    <br><br>
    <footer><hr>BE Project<br>Diabetic Retinopathy Detection <br>Group 23 <br> <br></footer>
    
</body>

</html>

DiabeticRetinopathy/templates/DiabeticRetinopathy/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>dr-detection</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
     {% load static %}
    <link rel="stylesheet" href="{% static 'DiabeticRetinopathy/style.css' %}">
</head>

<body>

    <nav class="navbar bg-dark navbar-expand-sm">
        <div class="container-fluid">
          <div class="navbar-header">
            <a class="navbar-brand" href="upload.html"><i class="fa fa-eye" style="font-size: 35px; "></i></a>
          </div>
          
          <ul class="nav navbar-nav navbar-right">
            <li class="nav-item"><a href="{% url 'DR:user_logout' %}"><be>Logout</b></a></li>

            <li class="nav-item"><a href="#"><be>About</b></a></li>
            <li class="nav-item"><a href="{% url 'DR:teamview' %}"><be>Team</b></a></li>
          </ul>
        </div>
    </nav>

    <br><br>


    



    <div id="upload-section">

        <div class="jumbotron">

            <div class="header">
                <i class="fa fa-upload icon" style="display: inline-block;"> UPLOAD FUNDUS</i>
            </div>
        
        </div>
        <br>
        <div class="jumbotron">
            <div class="upload-body">

 <form action="" enctype="multipart/form-data" method="post">
     {% csrf_token %}
                <div id="info-table" class="info-table">

                    <table>
                        <tr>
                            <td>First Name</td>
                            <td></td>
                            <td>{{ reportform.first_name }}</td>
                            
                        </tr>
                        <tr>
                            <td>Last Name</td>
                            <td></td>
                            <td>{{ reportform.last_name }}</td>
                            
                        </tr>
                        
                        <tr>
                            <td>Age</td>
                            <td></td>
                            <td>{{ reportform.age }}</td>
                        </tr>
                        
                        <tr>
                            <td>Gender</td>
                            <td></td>
                            <td>{{ reportform.gender }}</td>
                        </tr>

                        
                        
                        <tr>

                        </tr>
                    
                    </table> 

                        
                </div>
                <br><br>
                <label for="fundus-upload" class="btn btn-outline-light btn-add upload-btn">Upload</label>
                <input type="file" name="{{ reportform.photo.name }}" id="fundus-upload" class="fundus-upload" accept=".jpg, .jpeg, .png" style="display: none;">
                <br><br>
                <div class="fundus-preview" style="margin-left: auto; margin-right: auto;">
                    <p>Image not yet uploaded...</p>
                </div>

                <br>
                <div class="fundus-submit">
                    <input type="submit" name="upload" class="btn btn-outline-light btn-add" value="Submit">
                </div>
     </form>
            </div>

        </div>




    </div>
    <br><br>
    <footer><hr>BE Project<br>Diabetic Retinopathy Detection <br>Group 23 <br> <br></footer>


</body>

<script>

    const input = document.querySelector('.fundus-upload');
    const preview = document.querySelector('.fundus-preview');

    input.style.opacity = 0;

    const fileTypes = [
        'image/jpeg',
        'image/pjpeg',
        'image/png'
    ];

    function validFileType(file) 
    {
        return fileTypes.includes(file.type);
    }

    function returnFileSize(number) 
    {
        if(number < 1024) 
        {
            return number + 'bytes';
        } 
        else if(number >= 1024 && number < 1048576) 
        {
            return (number/1024).toFixed(1) + 'KB';
        } 
        else if(number >= 1048576) 
        {
            return (number/1048576).toFixed(1) + 'MB';
        }
    }

    input.addEventListener('change', updateImageDisplay);

    function updateImageDisplay()
    {

        while(preview.firstChild) 
        {
            preview.removeChild(preview.firstChild);
        }

        const curFiles = input.files;
        if(curFiles.length === 0)
        {
            const para = document.createElement('p');
            para.textContent = 'No Image Selected....';
            preview.appendChild(list);
        }
        else{
            const list = document.createElement('ol');
            preview.appendChild(list);

            for(const file of curFiles)
            {
                const listItem = document.createElement('li');
                const para = document.createElement('p');
                if(validFileType(file)) 
                {
                    para.textContent = `File Name: ${file.name}, File Size: ${returnFileSize(file.size)}.`;
                    const image = document.createElement('img');
                    image.src = URL.createObjectURL(file);

                    listItem.appendChild(image);
                    listItem.appendChild(para);
                } 
                else {
                    para.textContent = `File name ${file.name}: Not a valid file type. Update your selection.`;
                    listItem.appendChild(para);
                }

                list.appendChild(listItem);
            }
        }
    }

</script>

</html>